# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: RSS
    url: https://xianmobilelab.github.io/atom.xml
  - name: Github
    url: https://github.com/xianmobilelab
  - name: ThoughtWorks
    url: https://www.thoughtworks.com

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives

# widgets
widgets:
  - links
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/xianmobilelab
- slug: rss
	url: /atom.xml
